#!/bin/zsh
#
#MOSBasic 
#
#   __  __  ____   _____ ____            _      
#  |  \/  |/ __ \ / ____|  _ \          (_)     
#  | \  / | |  | | (___ | |_) | __ _ ___ _  ___ 
#  | |\/| | |  | |\___ \|  _ < / _` / __| |/ __|
#  | |  | | |__| |____) | |_) | (_| \__ \ | (__ 
#  |_|  |_|\____/|_____/|____/ \__,_|___/_|\___|
#
# This file is dedicated to functions which could be called
# across the board through out all commands.
#
################################
#          FUNCTIONS           #
################################
cli_log() {
	LINE=$1
	TODAY=`date '+%a %x %X'`
	#Print on stdout
	echo "$TODAY =====>$LINE"
	#Log to file
	echo "$CMDRAN ++> $TODAY =====> $LINE" >> $LOG
}

cli_graffitti() {
	echo '   __  __  ____   _____ ____            _       '
	echo '  |  \/  |/ __ \ / ____|  _ \          (_)      '
	echo '  | \  / | |  | | (___ | |_) | __ _ ___ _  ___  '
	echo '  | |\/| | |  | |\___ \|  _ < / _` / __| |/ __| '
	echo '  | |  | | |__| |____) | |_) | (_| \__ \ | (__  '
	echo '  |_|  |_|\____/|_____/|____/ \__,_|___/_|\___| '

}

ParseIt_ios() {
	UDID=$(echo "$line" | cut -f 1 -d$'\t')
	DeviceSerialNumber=$(echo "$line" | cut -f 2 -d$'\t')
	CURRENTNAME=$(echo "$line" | cut -f 3 -d$'\t')
	TAGS=$(echo "$line" | cut -f 4 -d$'\t')
	ASSETTAG=$(echo "$line" | cut -f 5 -d$'\t')
	LASTCHECKIN=$(echo "$line" | cut -f 6 -d$'\t')
	ENROLLMENT_TYPE=$(echo "$line" | cut -f 7 -d$'\t')
	USERID=$(echo "$line" | cut -f 8 -d$'\t')
	NAME=$(echo "$line" | cut -f 9 -d$'\t')
}

#ColorCodes
Red=`tput setaf 1`
Green=`tput setaf 2`
Yellow=`tput setaf 3`
Blue=`tput setaf 4`
Magenta=`tput setaf 5`
Cyan=`tput setaf 6`
White=`tput setaf 7`
reset=`tput sgr0`